---
# Step 2: Expose the Deployment
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
# Step 1: Create HTTPD Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 5  # Number of instances of HTTPD running
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
    containers:
        - name: httpd
          image: httpd:latest
          ports:
            - containerPort: 8080
